[package]
name = "crypto"
version = "0.1.0"
authors = ["Jonas Geschke <github@yonny.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
